name: Regular commiting

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 1 * * */5'

# ONLY EVER RUN ONE AT A TIME
concurrency: ${{ github.workflow }}

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        name: Checkout Code
        with:
          fetch-depth: 1
      - run: "date > .metadata"

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Updating metadata"
          commit_user_name: David Collom [Auto]
          commit_user_email: david@collom.co.uk
          file_pattern: ".metadata"
          skip_checkout: true
