name: Regular commiting

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 1 * * */5'

# ONLY EVER RUN ONE AT A TIME
concurrency: ${{ github.workflow }}

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code
        with:
          fetch-depth: 1
      - run: "date > .metadata"
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          title: Automated Regular Commit
          author: David Collom [Auto] <david@collom.co.uk>
          signoff: true
          branch: "${GITHUB_RUN_ID}"
          delete-branch: true
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash
